import {
  TOGETHER_ARTICLE_FEATURED_IMAGE_PROMPT,
  TOGETHER_CATEGORY_COVER_PROMPT,
  TOGETHER_HERO_BANNER_NEGATIVE,
  TOGETHER_HERO_BANNER_PROMPT,
  TOGETHER_SITE_LOGO_PROMPT,
  type TogetherImagePromptKey,
} from '@/utilities/domainGeneration/promptKeys'
import { heroBannerImageNegativePrompt } from '@/utilities/heroBannerMedia'
import {
  TOGETHER_ARTICLE_FEATURED_IMAGE_PROMPT_TEMPLATE,
  TOGETHER_CATEGORY_COVER_PROMPT_TEMPLATE,
  TOGETHER_HERO_BANNER_PROMPT_TEMPLATE,
  TOGETHER_SITE_LOGO_PROMPT_TEMPLATE,
} from '@/utilities/togetherTenantPrompts/togetherImagePromptTemplates'

export const DEFAULT_TOGETHER_IMAGE_PROMPT_SEED_BODIES: Record<TogetherImagePromptKey, string> = {
  [TOGETHER_SITE_LOGO_PROMPT]: TOGETHER_SITE_LOGO_PROMPT_TEMPLATE,
  [TOGETHER_HERO_BANNER_PROMPT]: TOGETHER_HERO_BANNER_PROMPT_TEMPLATE,
  [TOGETHER_HERO_BANNER_NEGATIVE]: heroBannerImageNegativePrompt(),
  [TOGETHER_CATEGORY_COVER_PROMPT]: TOGETHER_CATEGORY_COVER_PROMPT_TEMPLATE,
  [TOGETHER_ARTICLE_FEATURED_IMAGE_PROMPT]: TOGETHER_ARTICLE_FEATURED_IMAGE_PROMPT_TEMPLATE,
}
