import {
  CONTENT_WORKFLOW_MESSAGE_SITE_RUNNER,
  contentWorkflowOrigin,
  enqueueContentWorkflowMessage,
  type ContentWorkflowQueueEnv,
  type ContentWorkflowQueueMessage,
} from '@/utilities/contentWorkflowQueue'

// Generated by `opennextjs-cloudflare build`; absent before the first build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- .open-next is generated after Next build in clean worktrees.
// @ts-ignore .open-next is generated at build time.
import nextWorker from '../.open-next/worker.js'

type WorkerEnv = CloudflareEnv &
  ContentWorkflowQueueEnv & {
    PAYLOAD_SECRET?: string
    PIPELINE_BASE_URL?: string
    PAYLOAD_PUBLIC_SERVER_URL?: string
  }

function isSiteRunnerMessage(value: unknown): value is ContentWorkflowQueueMessage {
  if (!value || typeof value !== 'object') return false
  const o = value as Record<string, unknown>
  return (
    o.type === CONTENT_WORKFLOW_MESSAGE_SITE_RUNNER &&
    typeof o.siteId === 'number' &&
    (typeof o.runnerJobId === 'number' || typeof o.runnerJobId === 'string') &&
    Boolean(o.input && typeof o.input === 'object')
  )
}

async function runSiteRunnerChunk(
  message: ContentWorkflowQueueMessage,
  env: WorkerEnv,
  ctx: ExecutionContext,
): Promise<{ shouldContinue: boolean }> {
  const secret = env.PAYLOAD_SECRET?.trim()
  if (!secret) {
    throw new Error('PAYLOAD_SECRET is not configured for content workflow queue')
  }

  const origin = contentWorkflowOrigin(env)
  const res = await nextWorker.fetch(
    new Request(`${origin}/api/pipeline/site-content-runner`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-internal-token': secret,
      },
      body: JSON.stringify({
        siteId: message.siteId,
        runnerJobId: message.runnerJobId,
        partialAsRunning: true,
        batchMaxRuns: message.input.batchMaxRuns ?? 10,
        batchBudgetMs: message.input.batchBudgetMs ?? 50_000,
        maxBatches: Math.min(message.input.maxBatches ?? 3, 3),
        stopOnFailure: message.input.stopOnFailure !== false,
      }),
    }),
    env,
    ctx,
  )

  const data = (await res.json().catch(() => ({}))) as {
    ok?: boolean
    pendingRemaining?: number
    stoppedReason?: string
    failureSummary?: string
  }

  if (!res.ok || data.ok === false) {
    const reason = data.failureSummary || data.stoppedReason || `HTTP ${res.status}`
    throw new Error(`site content runner failed: ${reason}`)
  }

  return {
    shouldContinue:
      typeof data.pendingRemaining === 'number' &&
      data.pendingRemaining > 0 &&
      (data.stoppedReason === 'max_batches' ||
        data.stoppedReason === 'budget' ||
        data.stoppedReason === 'max_runs'),
  }
}

async function kickContentWorkflow(env: WorkerEnv, ctx: ExecutionContext): Promise<void> {
  const secret = env.PAYLOAD_SECRET?.trim()
  if (!secret) return
  const origin = contentWorkflowOrigin(env)
  const res = await nextWorker.fetch(
    new Request(`${origin}/api/pipeline/content-workflow/kick`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-internal-token': secret,
      },
      body: JSON.stringify({ limit: 25 }),
    }),
    env,
    ctx,
  )
  if (!res.ok) {
    console.error('[content-workflow] scheduled kick failed', res.status, await res.text())
  }
}

const worker: ExportedHandler<WorkerEnv, ContentWorkflowQueueMessage> = {
  fetch(request, env, ctx) {
    return nextWorker.fetch(request, env, ctx)
  },

  async queue(batch, env, ctx) {
    for (const message of batch.messages) {
      try {
        if (!isSiteRunnerMessage(message.body)) {
          console.warn('[content-workflow] unknown queue message', message.id)
          continue
        }

        const result = await runSiteRunnerChunk(message.body, env, ctx)
        if (result.shouldContinue && env.CONTENT_WORKFLOW_QUEUE) {
          await enqueueContentWorkflowMessage(
            env.CONTENT_WORKFLOW_QUEUE,
            {
              ...message.body,
              attempt: (message.body.attempt ?? 0) + 1,
              input: {
                ...message.body.input,
                maxBatches: Math.min(message.body.input.maxBatches ?? 3, 3),
              },
            },
            { delaySeconds: 5 },
          )
        }
      } catch (e) {
        console.error('[content-workflow] queue message failed', {
          messageId: message.id,
          attempts: message.attempts,
          error: e instanceof Error ? e.message : String(e),
        })
        message.retry({ delaySeconds: Math.min(300, 20 + message.attempts * 20) })
      }
    }
  },

  scheduled(_controller, env, ctx) {
    ctx.waitUntil(kickContentWorkflow(env, ctx))
  },
}

export default worker
